services:
  web:
    container_name: api_nest
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
    environment:
      DATABASE_HOST: db
      SECRET: Rl3Ucrr3LVkWU52UDqJAGUpy8sk2Tu6f8b3CrKWsOuTQT0qGJA
      DATABASE_PORT: 3306
      DATABASE_USER: root
      TOKEN_WEB_API: eyJhbGciOiJIUzIZ1NiJ9.eyJhdWQiOiJhNGNlMmQ2MDE0NDhkYzI0YjNmOThkMGIyMGY0YjY0MyIsIm5iZiI6MTcyNjE4ODg4NS4xNTY5MDksInN1YiI6IjY2NTkwMzAzOWNkNDFiMjg3YTkzZWQ0NiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Pc-wd8a8_D5MDF5dzpfcldbDasLdxhj-K7EF7G6QY5A 
      DATABASE_PASSWORD: root_password
      DATABASE_NAME: desarrollo
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: desarrollo
      MYSQL_PASSWORD: desarrollo
      MYSQL_DATABASE: desarrollo
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql


  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data



volumes:
  data:
  cache:

