services:
  web:
    container_name: api_nest
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      SECRET: Rl3Ucrr3LVkWU52UDqJAGUpy8sk2Tu6f8b3CrKWsOuTQT0qGJA
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root_password
      DATABASE_NAME: desarrollo

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: desarrollo
      MYSQL_PASSWORD: desarrollo
      MYSQL_DATABASE: desarrollo
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
